- name: Deploying Reddit app
  hosts: app
  become: true

  tasks:

    - name: Clone reddit reposirory
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/{{ deploy_user }}/reddit
        version: monolith # <-- branch
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/{{ deploy_user }}/reddit # <-- В какой директории выполнить команду bundle

  handlers:

    - name: reload puma
      systemd: name=puma state=restarted
