- name: Deploying Reddit app
  hosts: app
  become: true
  vars:
    db_host: 10.166.0.53
  tasks:

    - name: Clone reddit reposirory
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith # <-- branch
      notify: restart puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit # <-- В какой директории выполнить команду bundle

  handlers:

    - name: restart puma
      systemd: name=puma state=restarted
