- name: Install Ruby && Bundler
  hosts: all
  become: true
  tasks:
    - name: Install ruby and bundle
      apt:
        name: ["ruby-full", "ruby-bundler", "build-essential"]
        update_cache: yes
